# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfDlpDecode < Formula
  desc "Cloudflare DLP Forensic Copy Decoder"
  homepage "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.3.0/cloudflare-dlp-forensic-copy-decoder_Darwin_x86_64.tar.gz"
      sha256 "0d52b39731ddba515e0563412ffc65a513d6cf8aa7a1a69f2e1409d10b90c26f"

      define_method(:install) do
        bin.install "cf-dlp-decode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.3.0/cloudflare-dlp-forensic-copy-decoder_Darwin_arm64.tar.gz"
      sha256 "654db944f465ddaf0a0307b1089b7239278f9d744808cc778f7179fed6ede2ab"

      define_method(:install) do
        bin.install "cf-dlp-decode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.3.0/cloudflare-dlp-forensic-copy-decoder_Linux_x86_64.tar.gz"
      sha256 "0d4942fc9a7d44119930c00e4465c4d0ad859d82139083712487c083471d88f3"
      define_method(:install) do
        bin.install "cf-dlp-decode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.3.0/cloudflare-dlp-forensic-copy-decoder_Linux_arm64.tar.gz"
      sha256 "8507a4f0a91cdd5ede30b8d8e1354de89ea935043a9376acea94eb4f1f73e8ff"
      define_method(:install) do
        bin.install "cf-dlp-decode"
      end
    end
  end

  test do
    system "#{bin}/cf-dlp-decode", "--version"
  end
end
