# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfDlpDecode < Formula
  desc "Cloudflare DLP Forensic Copy Decoder"
  homepage "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.0.1/cloudflare-dlp-forensic-copy-decoder_Darwin_x86_64.tar.gz"
      sha256 "52fe0f1a30ec235844a5aeb5c66144c3d25904d33b8434ebaa286a302856034a"

      def install
        bin.install "cf-dlp-decode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.0.1/cloudflare-dlp-forensic-copy-decoder_Darwin_arm64.tar.gz"
      sha256 "98bedc735264d0f494d91bbe012e238ad03c921e513bd856b577bf21a3fc3def"

      def install
        bin.install "cf-dlp-decode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.0.1/cloudflare-dlp-forensic-copy-decoder_Linux_x86_64.tar.gz"
      sha256 "91596ae8f292430c6fe16b1bcc7055409366e4058f19ecb560d5ac332d63b6f1"
      def install
        bin.install "cf-dlp-decode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.0.1/cloudflare-dlp-forensic-copy-decoder_Linux_arm64.tar.gz"
      sha256 "7666965c086aac25bee1df005500e545b583a03742a4b8858f8aa8ab96266c66"
      def install
        bin.install "cf-dlp-decode"
      end
    end
  end

  test do
    system "#{bin}/cf-dlp-decode", "--version"
  end
end
