# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfDlpDecode < Formula
  desc "Cloudflare DLP Forensic Copy Decoder"
  homepage "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.2.0/cloudflare-dlp-forensic-copy-decoder_Darwin_x86_64.tar.gz"
      sha256 "c3158a82f05573a078fd995e85916344aa9d2e516bfb1a713314935d0ec6718b"

      define_method(:install) do
        bin.install "cf-dlp-decode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.2.0/cloudflare-dlp-forensic-copy-decoder_Darwin_arm64.tar.gz"
      sha256 "559f1c78039c3389c2060c1de38f8ad6657d3f7f4641d60e6457c47cbe39a189"

      define_method(:install) do
        bin.install "cf-dlp-decode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.2.0/cloudflare-dlp-forensic-copy-decoder_Linux_x86_64.tar.gz"
      sha256 "9c99009d275ed4f3c374ef93d934d7f1b9e84947d08da6975b47902bde90f590"
      define_method(:install) do
        bin.install "cf-dlp-decode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Devolvio-B-V/cloudflare-dlp-forensic-copy-decoder/releases/download/v2.2.0/cloudflare-dlp-forensic-copy-decoder_Linux_arm64.tar.gz"
      sha256 "1ad6494fe89fed418e090042808e27c8f1d51bc05df84714daa45e648d51aa53"
      define_method(:install) do
        bin.install "cf-dlp-decode"
      end
    end
  end

  test do
    system "#{bin}/cf-dlp-decode", "--version"
  end
end
